# Generated by Django 5.0.6 on 2024-06-02 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_dias', models.IntegerField()),
                ('companhia', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_viagem', models.CharField(max_length=255)),
                ('numero_total_hospedes', models.IntegerField()),
                ('acompanhantes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('receita', 'Receita'), ('despesa', 'Despesa')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkout', models.DateField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='core.checkin')),
            ],
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('tipo_cliente', models.CharField(choices=[('individual', 'Individual'), ('empresa', 'Empresa')], max_length=10)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='hospede_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_principal', to='core.hospede'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='hospedes_secundarios',
            field=models.ManyToManyField(blank=True, related_name='checkins_secundarios', to='core.hospede'),
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_quarto', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('livre', 'Livre'), ('ocupado', 'Ocupado'), ('reservado', 'Reservado')], max_length=10)),
                ('checkin', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarto_checkin', to='core.checkin')),
                ('hospede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartos', to='core.hospede')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.quarto'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('hospede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.quarto')),
            ],
        ),
    ]
