# Generated by Django 5.0.6 on 2024-05-30 20:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='data_checkout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quarto',
            name='checkin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarto_checkin', to='core.checkin'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartos', to='core.hospede'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='data_checkin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='hospede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.hospede'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='core.quarto'),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='checkin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='core.checkin'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.hospede'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.quarto'),
        ),
    ]
