# Generated by Django 5.0.6 on 2024-06-10 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_checkin_numero_total_hospedes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], default='ativo', max_length=10),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='core.hospede'),
        ),
    ]
