# Generated by Django 5.0.6 on 2024-06-10 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reserva_status_alter_reserva_hospede'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='contato_hospede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nome_hospede',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hospede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='core.hospede'),
        ),
    ]
