# Generated by Django 5.0.6 on 2024-07-06 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserva_contato_hospede_reserva_nome_hospede_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='checkin',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='contato_hospede',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_hospede',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CheckinEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_dias', models.IntegerField()),
                ('companhia', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_viagem', models.CharField(max_length=255)),
                ('acompanhantes', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_empresa', to='core.empresa')),
                ('hospede_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_empresa_principal', to='core.hospede')),
                ('hospedes_secundarios', models.ManyToManyField(blank=True, related_name='checkins_secundarios_empresa', to='core.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_empresa', to='core.quarto')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkin_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='core.checkinempresa'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='checkin_empresa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarto_checkin_empresa', to='core.checkinempresa'),
        ),
        migrations.CreateModel(
            name='CheckinIndividual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField()),
                ('data_checkout', models.DateField()),
                ('diaria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_dias', models.IntegerField()),
                ('companhia', models.CharField(blank=True, max_length=255, null=True)),
                ('motivo_viagem', models.CharField(max_length=255)),
                ('acompanhantes', models.TextField(blank=True, null=True)),
                ('hospede_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_individual', to='core.hospede')),
                ('hospedes_secundarios', models.ManyToManyField(blank=True, related_name='checkins_secundarios_individual', to='core.hospede')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_individual', to='core.quarto')),
            ],
        ),
        migrations.AddField(
            model_name='checkout',
            name='checkin_individual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='core.checkinindividual'),
        ),
        migrations.AddField(
            model_name='quarto',
            name='checkin_individual',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarto_checkin_individual', to='core.checkinindividual'),
        ),
        migrations.DeleteModel(
            name='Checkin',
        ),
    ]
