# Generated by Django 5.0.6 on 2024-07-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_hospede_tipo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='tipo_checkin',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('empresa', 'Empresa')], max_length=10, null=True),
        ),
    ]
