# Generated by Django 5.0.6 on 2024-07-07 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quarto_tipo_checkin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quarto',
            name='hospede',
        ),
    ]
